# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Ago' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'SVProgressHUD'
  pod 'GZIP', '~> 1.2'
  pod 'ZipArchive', '~> 1.4.0'
  pod 'AgoraRtcEngine_iOS'
  pod 'YYModel'
end
