// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplyLogin_LoginType int32

const (
	ApplyLogin_MOBILE ApplyLogin_LoginType = 0
	ApplyLogin_HOME   ApplyLogin_LoginType = 1
	ApplyLogin_WORK   ApplyLogin_LoginType = 2
)

var ApplyLogin_LoginType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var ApplyLogin_LoginType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x ApplyLogin_LoginType) String() string {
	return proto.EnumName(ApplyLogin_LoginType_name, int32(x))
}

func (ApplyLogin_LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0, 0}
}

// 登陆请求
type ApplyLogin struct {
	//登陆账户
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	//登陆密码
	Password             string               `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Type                 ApplyLogin_LoginType `protobuf:"varint,3,opt,name=type,proto3,enum=login.ApplyLogin_LoginType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApplyLogin) Reset()         { *m = ApplyLogin{} }
func (m *ApplyLogin) String() string { return proto.CompactTextString(m) }
func (*ApplyLogin) ProtoMessage()    {}
func (*ApplyLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *ApplyLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyLogin.Unmarshal(m, b)
}
func (m *ApplyLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyLogin.Marshal(b, m, deterministic)
}
func (m *ApplyLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyLogin.Merge(m, src)
}
func (m *ApplyLogin) XXX_Size() int {
	return xxx_messageInfo_ApplyLogin.Size(m)
}
func (m *ApplyLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyLogin proto.InternalMessageInfo

func (m *ApplyLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ApplyLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ApplyLogin) GetType() ApplyLogin_LoginType {
	if m != nil {
		return m.Type
	}
	return ApplyLogin_MOBILE
}

//登陆请求返回
type ReplyLogin struct {
	Errinfo              string   `protobuf:"bytes,1,opt,name=errinfo,proto3" json:"errinfo,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyLogin) Reset()         { *m = ReplyLogin{} }
func (m *ReplyLogin) String() string { return proto.CompactTextString(m) }
func (*ReplyLogin) ProtoMessage()    {}
func (*ReplyLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *ReplyLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyLogin.Unmarshal(m, b)
}
func (m *ReplyLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyLogin.Marshal(b, m, deterministic)
}
func (m *ReplyLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyLogin.Merge(m, src)
}
func (m *ReplyLogin) XXX_Size() int {
	return xxx_messageInfo_ReplyLogin.Size(m)
}
func (m *ReplyLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyLogin proto.InternalMessageInfo

func (m *ReplyLogin) GetErrinfo() string {
	if m != nil {
		return m.Errinfo
	}
	return ""
}

func (m *ReplyLogin) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterEnum("login.ApplyLogin_LoginType", ApplyLogin_LoginType_name, ApplyLogin_LoginType_value)
	proto.RegisterType((*ApplyLogin)(nil), "login.ApplyLogin")
	proto.RegisterType((*ReplyLogin)(nil), "login.ReplyLogin")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x16, 0x30, 0x72, 0x71,
	0x39, 0x16, 0x14, 0xe4, 0x54, 0xfa, 0x80, 0xb8, 0x42, 0x12, 0x5c, 0xec, 0x89, 0xc9, 0xc9, 0xf9,
	0xa5, 0x79, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x14, 0x17, 0x47,
	0x41, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04, 0x13, 0x58, 0x0a, 0xce, 0x17, 0xd2, 0xe7,
	0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x33, 0x92, 0xd6, 0x83, 0xd8,
	0x83, 0x30, 0x56, 0x0f, 0x4c, 0x86, 0x54, 0x16, 0xa4, 0x06, 0x81, 0x15, 0x2a, 0x69, 0x73, 0x71,
	0xc2, 0x85, 0x84, 0xb8, 0xb8, 0xd8, 0x7c, 0xfd, 0x9d, 0x3c, 0x7d, 0x5c, 0x05, 0x18, 0x84, 0x38,
	0xb8, 0x58, 0x3c, 0xfc, 0x7d, 0x5d, 0x05, 0x18, 0x41, 0xac, 0x70, 0xff, 0x20, 0x6f, 0x01, 0x26,
	0x25, 0x2b, 0x2e, 0xae, 0xa0, 0x54, 0x64, 0x17, 0xa6, 0x16, 0x15, 0x65, 0xe6, 0xa5, 0xe5, 0xc3,
	0x5c, 0x08, 0xe5, 0x0a, 0x09, 0x71, 0xb1, 0x24, 0xe7, 0xa7, 0xa4, 0x82, 0x5d, 0xc7, 0x1a, 0x04,
	0x66, 0x27, 0xb1, 0x81, 0x3d, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x47, 0x83, 0x65, 0x72,
	0xfb, 0x00, 0x00, 0x00,
}
