// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roominfo.proto

package login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomType int32

const (
	RoomType_roomType_NOAML  RoomType = 0
	RoomType_roomType_SECOND RoomType = 1
)

var RoomType_name = map[int32]string{
	0: "roomType_NOAML",
	1: "roomType_SECOND",
}

var RoomType_value = map[string]int32{
	"roomType_NOAML":  0,
	"roomType_SECOND": 1,
}

func (x RoomType) String() string {
	return proto.EnumName(RoomType_name, int32(x))
}

func (RoomType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_58937e66e75f30e9, []int{0}
}

type ApplyCreateRoom struct {
	RoomName             string   `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName,omitempty"`
	RoomTags             string   `protobuf:"bytes,2,opt,name=roomTags,proto3" json:"roomTags,omitempty"`
	Roomtype             RoomType `protobuf:"varint,4,opt,name=roomtype,proto3,enum=login.RoomType" json:"roomtype,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyCreateRoom) Reset()         { *m = ApplyCreateRoom{} }
func (m *ApplyCreateRoom) String() string { return proto.CompactTextString(m) }
func (*ApplyCreateRoom) ProtoMessage()    {}
func (*ApplyCreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_58937e66e75f30e9, []int{0}
}

func (m *ApplyCreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyCreateRoom.Unmarshal(m, b)
}
func (m *ApplyCreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyCreateRoom.Marshal(b, m, deterministic)
}
func (m *ApplyCreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyCreateRoom.Merge(m, src)
}
func (m *ApplyCreateRoom) XXX_Size() int {
	return xxx_messageInfo_ApplyCreateRoom.Size(m)
}
func (m *ApplyCreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyCreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyCreateRoom proto.InternalMessageInfo

func (m *ApplyCreateRoom) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *ApplyCreateRoom) GetRoomTags() string {
	if m != nil {
		return m.RoomTags
	}
	return ""
}

func (m *ApplyCreateRoom) GetRoomtype() RoomType {
	if m != nil {
		return m.Roomtype
	}
	return RoomType_roomType_NOAML
}

type ApplyEnterRoom struct {
	RoomID               int64           `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	RoomName             string          `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	UrmIcon              string          `protobuf:"bytes,3,opt,name=urmIcon,proto3" json:"urmIcon,omitempty"`
	MasterID             int64           `protobuf:"varint,4,opt,name=masterID,proto3" json:"masterID,omitempty"`
	RoomUserInfo         []*RoomUserInfo `protobuf:"bytes,5,rep,name=RoomUserInfo,proto3" json:"RoomUserInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ApplyEnterRoom) Reset()         { *m = ApplyEnterRoom{} }
func (m *ApplyEnterRoom) String() string { return proto.CompactTextString(m) }
func (*ApplyEnterRoom) ProtoMessage()    {}
func (*ApplyEnterRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_58937e66e75f30e9, []int{1}
}

func (m *ApplyEnterRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyEnterRoom.Unmarshal(m, b)
}
func (m *ApplyEnterRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyEnterRoom.Marshal(b, m, deterministic)
}
func (m *ApplyEnterRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyEnterRoom.Merge(m, src)
}
func (m *ApplyEnterRoom) XXX_Size() int {
	return xxx_messageInfo_ApplyEnterRoom.Size(m)
}
func (m *ApplyEnterRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyEnterRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyEnterRoom proto.InternalMessageInfo

func (m *ApplyEnterRoom) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *ApplyEnterRoom) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *ApplyEnterRoom) GetUrmIcon() string {
	if m != nil {
		return m.UrmIcon
	}
	return ""
}

func (m *ApplyEnterRoom) GetMasterID() int64 {
	if m != nil {
		return m.MasterID
	}
	return 0
}

func (m *ApplyEnterRoom) GetRoomUserInfo() []*RoomUserInfo {
	if m != nil {
		return m.RoomUserInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("login.RoomType", RoomType_name, RoomType_value)
	proto.RegisterType((*ApplyCreateRoom)(nil), "login.ApplyCreateRoom")
	proto.RegisterType((*ApplyEnterRoom)(nil), "login.applyEnterRoom")
}

func init() { proto.RegisterFile("roominfo.proto", fileDescriptor_58937e66e75f30e9) }

var fileDescriptor_58937e66e75f30e9 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xcd, 0xea, 0xa6, 0x46, 0x69, 0x47, 0x06, 0x12, 0x76, 0x2a, 0x3b, 0x15, 0x85, 0x1e,
	0xb6, 0x83, 0xe7, 0xb1, 0xee, 0x50, 0xd0, 0x0e, 0xa2, 0x9e, 0x25, 0xca, 0xdb, 0x18, 0x2c, 0x79,
	0x21, 0xcd, 0x84, 0xfe, 0x5d, 0xfe, 0x83, 0x92, 0xac, 0xeb, 0x9c, 0xb7, 0x7c, 0xef, 0xf7, 0x3d,
	0xbe, 0x2f, 0x8f, 0xc6, 0x16, 0x51, 0x6d, 0xf5, 0x1a, 0x73, 0x63, 0xd1, 0x21, 0xeb, 0xef, 0x70,
	0xb3, 0xd5, 0xe3, 0x78, 0x5f, 0x83, 0x3d, 0x8d, 0x27, 0xdf, 0x34, 0x99, 0x1b, 0xb3, 0x6b, 0x16,
	0x16, 0xa4, 0x03, 0x81, 0xa8, 0xd8, 0x98, 0x5e, 0xfb, 0xdd, 0x4a, 0x2a, 0xe0, 0x24, 0x25, 0xd9,
	0x8d, 0xe8, 0xf4, 0x91, 0xbd, 0xc9, 0x4d, 0xcd, 0x7b, 0x27, 0xe6, 0x35, 0x7b, 0x3c, 0x30, 0xd7,
	0x18, 0xe0, 0x97, 0x29, 0xc9, 0xe2, 0x69, 0x92, 0x87, 0xd0, 0x3c, 0x58, 0x1a, 0x03, 0xa2, 0x33,
	0x4c, 0x7e, 0x08, 0x8d, 0xa5, 0x0f, 0x5e, 0x6a, 0x07, 0x36, 0xe4, 0xde, 0xd3, 0x81, 0xc7, 0x65,
	0x11, 0x52, 0x23, 0xd1, 0xaa, 0xb3, 0x3e, 0xbd, 0x7f, 0x7d, 0x38, 0xbd, 0xda, 0x5b, 0x55, 0x7e,
	0xa1, 0xe6, 0x51, 0x40, 0x47, 0xe9, 0xb7, 0x94, 0xac, 0x1d, 0xd8, 0xb2, 0x08, 0x6d, 0x22, 0xd1,
	0x69, 0xf6, 0x44, 0xef, 0x7c, 0xe2, 0x7b, 0x0d, 0xb6, 0xd4, 0x6b, 0xe4, 0xfd, 0x34, 0xca, 0x6e,
	0xa7, 0xa3, 0xb6, 0xed, 0x5f, 0x24, 0xce, 0x8c, 0x0f, 0xb3, 0xf6, 0xfb, 0x8d, 0x01, 0xc6, 0x0e,
	0x27, 0xf6, 0xef, 0x8f, 0x6a, 0x35, 0x7f, 0x79, 0x1e, 0x5e, 0xb0, 0x11, 0x4d, 0xba, 0xd9, 0xeb,
	0x72, 0xb1, 0xaa, 0x8a, 0x21, 0xf9, 0x1c, 0x84, 0x4b, 0xcf, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x87, 0x4b, 0xbb, 0x26, 0x92, 0x01, 0x00, 0x00,
}
