// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Squart.proto

package login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TagInfo struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TagName              string   `protobuf:"bytes,2,opt,name=TagName,proto3" json:"TagName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagInfo) Reset()         { *m = TagInfo{} }
func (m *TagInfo) String() string { return proto.CompactTextString(m) }
func (*TagInfo) ProtoMessage()    {}
func (*TagInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c064b58cd87c1f, []int{0}
}

func (m *TagInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagInfo.Unmarshal(m, b)
}
func (m *TagInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagInfo.Marshal(b, m, deterministic)
}
func (m *TagInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagInfo.Merge(m, src)
}
func (m *TagInfo) XXX_Size() int {
	return xxx_messageInfo_TagInfo.Size(m)
}
func (m *TagInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TagInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TagInfo proto.InternalMessageInfo

func (m *TagInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TagInfo) GetTagName() string {
	if m != nil {
		return m.TagName
	}
	return ""
}

type TagsInfo struct {
	TagInfo              []*TagInfo `protobuf:"bytes,1,rep,name=TagInfo,proto3" json:"TagInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TagsInfo) Reset()         { *m = TagsInfo{} }
func (m *TagsInfo) String() string { return proto.CompactTextString(m) }
func (*TagsInfo) ProtoMessage()    {}
func (*TagsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c064b58cd87c1f, []int{1}
}

func (m *TagsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagsInfo.Unmarshal(m, b)
}
func (m *TagsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagsInfo.Marshal(b, m, deterministic)
}
func (m *TagsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagsInfo.Merge(m, src)
}
func (m *TagsInfo) XXX_Size() int {
	return xxx_messageInfo_TagsInfo.Size(m)
}
func (m *TagsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TagsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TagsInfo proto.InternalMessageInfo

func (m *TagsInfo) GetTagInfo() []*TagInfo {
	if m != nil {
		return m.TagInfo
	}
	return nil
}

//热门房间
type HotRoomInfo struct {
	RoomID               int64    `protobuf:"varint,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	RoomTagName          string   `protobuf:"bytes,2,opt,name=RoomTagName,proto3" json:"RoomTagName,omitempty"`
	RoomHot              int64    `protobuf:"varint,3,opt,name=RoomHot,proto3" json:"RoomHot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotRoomInfo) Reset()         { *m = HotRoomInfo{} }
func (m *HotRoomInfo) String() string { return proto.CompactTextString(m) }
func (*HotRoomInfo) ProtoMessage()    {}
func (*HotRoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c064b58cd87c1f, []int{2}
}

func (m *HotRoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotRoomInfo.Unmarshal(m, b)
}
func (m *HotRoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotRoomInfo.Marshal(b, m, deterministic)
}
func (m *HotRoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotRoomInfo.Merge(m, src)
}
func (m *HotRoomInfo) XXX_Size() int {
	return xxx_messageInfo_HotRoomInfo.Size(m)
}
func (m *HotRoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HotRoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HotRoomInfo proto.InternalMessageInfo

func (m *HotRoomInfo) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *HotRoomInfo) GetRoomTagName() string {
	if m != nil {
		return m.RoomTagName
	}
	return ""
}

func (m *HotRoomInfo) GetRoomHot() int64 {
	if m != nil {
		return m.RoomHot
	}
	return 0
}

type HotRooms struct {
	HotRoomInfo          []*HotRoomInfo `protobuf:"bytes,1,rep,name=HotRoomInfo,proto3" json:"HotRoomInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HotRooms) Reset()         { *m = HotRooms{} }
func (m *HotRooms) String() string { return proto.CompactTextString(m) }
func (*HotRooms) ProtoMessage()    {}
func (*HotRooms) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c064b58cd87c1f, []int{3}
}

func (m *HotRooms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotRooms.Unmarshal(m, b)
}
func (m *HotRooms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotRooms.Marshal(b, m, deterministic)
}
func (m *HotRooms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotRooms.Merge(m, src)
}
func (m *HotRooms) XXX_Size() int {
	return xxx_messageInfo_HotRooms.Size(m)
}
func (m *HotRooms) XXX_DiscardUnknown() {
	xxx_messageInfo_HotRooms.DiscardUnknown(m)
}

var xxx_messageInfo_HotRooms proto.InternalMessageInfo

func (m *HotRooms) GetHotRoomInfo() []*HotRoomInfo {
	if m != nil {
		return m.HotRoomInfo
	}
	return nil
}

type BannerInfo struct {
	BannerId             int32    `protobuf:"varint,1,opt,name=bannerId,proto3" json:"bannerId,omitempty"`
	TargetType           int32    `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	BgImg                string   `protobuf:"bytes,5,opt,name=bg_img,json=bgImg,proto3" json:"bg_img,omitempty"`
	ClickUrl             string   `protobuf:"bytes,6,opt,name=click_url,json=clickUrl,proto3" json:"click_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BannerInfo) Reset()         { *m = BannerInfo{} }
func (m *BannerInfo) String() string { return proto.CompactTextString(m) }
func (*BannerInfo) ProtoMessage()    {}
func (*BannerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c064b58cd87c1f, []int{4}
}

func (m *BannerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BannerInfo.Unmarshal(m, b)
}
func (m *BannerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BannerInfo.Marshal(b, m, deterministic)
}
func (m *BannerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BannerInfo.Merge(m, src)
}
func (m *BannerInfo) XXX_Size() int {
	return xxx_messageInfo_BannerInfo.Size(m)
}
func (m *BannerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BannerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BannerInfo proto.InternalMessageInfo

func (m *BannerInfo) GetBannerId() int32 {
	if m != nil {
		return m.BannerId
	}
	return 0
}

func (m *BannerInfo) GetTargetType() int32 {
	if m != nil {
		return m.TargetType
	}
	return 0
}

func (m *BannerInfo) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *BannerInfo) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *BannerInfo) GetBgImg() string {
	if m != nil {
		return m.BgImg
	}
	return ""
}

func (m *BannerInfo) GetClickUrl() string {
	if m != nil {
		return m.ClickUrl
	}
	return ""
}

type Banners struct {
	BannerInfo           []*BannerInfo `protobuf:"bytes,1,rep,name=BannerInfo,proto3" json:"BannerInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Banners) Reset()         { *m = Banners{} }
func (m *Banners) String() string { return proto.CompactTextString(m) }
func (*Banners) ProtoMessage()    {}
func (*Banners) Descriptor() ([]byte, []int) {
	return fileDescriptor_11c064b58cd87c1f, []int{5}
}

func (m *Banners) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Banners.Unmarshal(m, b)
}
func (m *Banners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Banners.Marshal(b, m, deterministic)
}
func (m *Banners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Banners.Merge(m, src)
}
func (m *Banners) XXX_Size() int {
	return xxx_messageInfo_Banners.Size(m)
}
func (m *Banners) XXX_DiscardUnknown() {
	xxx_messageInfo_Banners.DiscardUnknown(m)
}

var xxx_messageInfo_Banners proto.InternalMessageInfo

func (m *Banners) GetBannerInfo() []*BannerInfo {
	if m != nil {
		return m.BannerInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*TagInfo)(nil), "login.TagInfo")
	proto.RegisterType((*TagsInfo)(nil), "login.TagsInfo")
	proto.RegisterType((*HotRoomInfo)(nil), "login.HotRoomInfo")
	proto.RegisterType((*HotRooms)(nil), "login.HotRooms")
	proto.RegisterType((*BannerInfo)(nil), "login.BannerInfo")
	proto.RegisterType((*Banners)(nil), "login.Banners")
}

func init() { proto.RegisterFile("Squart.proto", fileDescriptor_11c064b58cd87c1f) }

var fileDescriptor_11c064b58cd87c1f = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x96, 0xa4, 0xe9, 0x05, 0x55, 0xc2, 0x12, 0xc8, 0x80, 0x10, 0x51, 0xa6, 0x4c,
	0x95, 0xa0, 0x1d, 0x19, 0x10, 0xea, 0xd0, 0x2c, 0x0c, 0x26, 0xcc, 0x91, 0xd3, 0x1a, 0x2b, 0x22,
	0x89, 0x8b, 0xe3, 0x0e, 0xfd, 0x65, 0xfc, 0x3d, 0xd4, 0xb3, 0x53, 0xd2, 0xcd, 0xef, 0x3d, 0x9f,
	0xef, 0x7b, 0x92, 0xe1, 0xf2, 0xe3, 0x67, 0xcf, 0xb5, 0x99, 0xef, 0xb4, 0x32, 0x8a, 0xf8, 0xb5,
	0x92, 0x55, 0x9b, 0x2c, 0x60, 0x92, 0x73, 0x99, 0xb5, 0x5f, 0x8a, 0xcc, 0x60, 0x94, 0xad, 0xa8,
	0x17, 0x7b, 0xe9, 0x98, 0x8d, 0xb2, 0x15, 0xa1, 0x18, 0xbd, 0xf3, 0x46, 0xd0, 0x51, 0xec, 0xa5,
	0x53, 0xd6, 0xcb, 0x64, 0x09, 0x61, 0xce, 0x65, 0x87, 0x53, 0xe9, 0xe9, 0x01, 0xea, 0xc5, 0xe3,
	0x34, 0x7a, 0x9e, 0xcd, 0xf1, 0xe5, 0xb9, 0x73, 0x59, 0x1f, 0x27, 0x1c, 0xa2, 0xb5, 0x32, 0x4c,
	0xa9, 0x06, 0x07, 0x6f, 0x20, 0xc0, 0x73, 0xbf, 0xd2, 0x29, 0x12, 0x43, 0x74, 0x3c, 0x9d, 0xaf,
	0x1e, 0x5a, 0x47, 0xb0, 0xa3, 0x5c, 0x2b, 0x43, 0xc7, 0x38, 0xda, 0xcb, 0xe4, 0x15, 0x42, 0xb7,
	0xa2, 0x23, 0xcb, 0xb3, 0x75, 0x0e, 0x8e, 0x38, 0xb8, 0x41, 0xc2, 0x86, 0xd7, 0x92, 0x5f, 0x0f,
	0xe0, 0x8d, 0xb7, 0xad, 0xd0, 0x08, 0x79, 0x07, 0x61, 0x69, 0xd5, 0x16, 0x31, 0x7d, 0x76, 0xd2,
	0xe4, 0x11, 0x22, 0xc3, 0xb5, 0x14, 0xa6, 0x30, 0x87, 0x9d, 0x05, 0xf5, 0x19, 0x58, 0x2b, 0x3f,
	0xec, 0x04, 0x79, 0x00, 0xe8, 0x0c, 0xd7, 0xa6, 0x30, 0x55, 0x23, 0x1c, 0xea, 0x14, 0x9d, 0xbc,
	0x6a, 0x04, 0xb9, 0x85, 0x50, 0xb4, 0x5b, 0x1b, 0x5e, 0xd8, 0x1e, 0xa2, 0xdd, 0x62, 0x74, 0x0d,
	0x41, 0x29, 0x8b, 0xaa, 0x91, 0xd4, 0xc7, 0xfa, 0x7e, 0x29, 0xb3, 0x46, 0x92, 0x7b, 0x98, 0x6e,
	0xea, 0x6a, 0xf3, 0x5d, 0xec, 0x75, 0x4d, 0x03, 0x4c, 0x42, 0x34, 0x3e, 0x75, 0x9d, 0xbc, 0xc0,
	0xc4, 0x82, 0x77, 0xe4, 0x69, 0xd8, 0xc1, 0x35, 0xbf, 0x72, 0xcd, 0xff, 0x03, 0x36, 0xb8, 0x54,
	0x06, 0xf8, 0x2b, 0x16, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x13, 0x66, 0x73, 0x3f, 0x25, 0x02,
	0x00, 0x00,
}
