// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userinfo.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class userInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UserinfoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface UserinfoRoot : GPBRootObject
@end

#pragma mark - userInfo

typedef GPB_ENUM(userInfo_FieldNumber) {
  userInfo_FieldNumber_PlayerId = 1,
  userInfo_FieldNumber_PlayerName = 2,
  userInfo_FieldNumber_Sex = 3,
  userInfo_FieldNumber_PlayerIcon = 4,
  userInfo_FieldNumber_TitleId = 5,
  userInfo_FieldNumber_TitleName = 6,
  userInfo_FieldNumber_Age = 7,
  userInfo_FieldNumber_Auth = 8,
  userInfo_FieldNumber_Sign = 9,
};

@interface userInfo : GPBMessage

@property(nonatomic, readwrite) int64_t playerId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *playerName;

@property(nonatomic, readwrite) int32_t sex;

@property(nonatomic, readwrite, copy, null_resettable) NSString *playerIcon;

@property(nonatomic, readwrite) int32_t titleId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *titleName;

@property(nonatomic, readwrite) int32_t age;

/** 1是已经认证 */
@property(nonatomic, readwrite) int32_t auth;

/** 签名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@end

#pragma mark - RoomUserInfo

typedef GPB_ENUM(RoomUserInfo_FieldNumber) {
  RoomUserInfo_FieldNumber_UserInfo = 1,
};

@interface RoomUserInfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) userInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@end

#pragma mark - OneUserinfo

typedef GPB_ENUM(OneUserinfo_FieldNumber) {
  OneUserinfo_FieldNumber_UserInfo = 1,
};

@interface OneUserinfo : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) userInfo *userInfo;
/** Test to see if @c userInfo has been set. */
@property(nonatomic, readwrite) BOOL hasUserInfo;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
